-- @description Toggle solo by track prefix (bundle)
-- @version 1.1
-- @changelog
--   * little improvements in the code
--   + the scripts are now located in their own folder
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [nomain] .
--  [main] sr_Toggle solo BUS01.lua
--  [main] sr_Toggle solo BUS02.lua
--  [main] sr_Toggle solo BUS03.lua
--  [main] sr_Toggle solo BUS04.lua
--  [main] sr_Toggle solo BUS05.lua
--  [main] sr_Toggle solo BUS06.lua
--  [main] sr_Toggle solo BUS07.lua
--  [main] sr_Toggle solo BUS08.lua
--  [main] sr_Toggle solo BUS09.lua
--  [main] sr_Toggle solo BUS10.lua
--  [main] sr_Toggle solo BUS11.lua
--  [main] sr_Toggle solo BUS12.lua
--  [main] sr_Toggle solo BUS13.lua
--  [main] sr_Toggle solo BUS14.lua
--  [main] sr_Toggle solo BUS15.lua
--  [main] sr_Toggle solo BUS16.lua
--  [main] sr_Toggle solo VCA01.lua
--  [main] sr_Toggle solo VCA02.lua
--  [main] sr_Toggle solo VCA03.lua
--  [main] sr_Toggle solo VCA04.lua
--  [main] sr_Toggle solo VCA05.lua
--  [main] sr_Toggle solo VCA06.lua
--  [main] sr_Toggle solo VCA07.lua
--  [main] sr_Toggle solo VCA08.lua
--  [main] sr_Toggle solo VCA09.lua
--  [main] sr_Toggle solo VCA10.lua
--  [main] sr_Toggle solo VCA11.lua
--  [main] sr_Toggle solo VCA12.lua
--  [main] sr_Toggle solo VCA13.lua
--  [main] sr_Toggle solo VCA14.lua
--  [main] sr_Toggle solo VCA15.lua
--  [main] sr_Toggle solo VCA16.lua
--  [nomain] sr_Toggle solo by track prefix function.lua
-- @about
--  # Description
--  - This script bundle consists of 32 scripts that will toggle solo tracks by their prefix.
--  - There are 16 BUS and VCA presets per default, but you can easily adjust or create your own presets by
--  editing the files.
--  - When adding the scripts to a toolbar, the buttons will reflect the toggle status.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923