-- @description Select CC (bundle)
-- @version 1.60
-- @changelog
--   + the scripts are now located in their own folder
--   * smaller bug fixes and improvements
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [nomain] .
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC64.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select all CCs.lua
--  [nomain] sr_Select CC function.lua
-- @about
--    # Description
--    * These scripts will select events in a specific CC lane or all CC lanes in one or multiple items.
--    * Assign the script in the main action list, as well. That way, the inline editor will be opened automatically, 
--    and you can see your selection in the arrange view.
--    * When hovering an inline editor, only the take under the mouse cursor will be affected, regardles of the item selection.
--    * You can easily customize the values in the scripts.
--    * The scripts work in the MIDI editor, inline editor and arrange view.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923