-- @description Human quantize notes (bundle)
-- @version 1.52
-- @changelog
--   + the scripts are now located in their own folder
--   * smaller bug fixes and improvements
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-1.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-2.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-4.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-4 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-8.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-8 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-16.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - 1-16 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] Human quantize notes (bundle)/sr_Human quantize notes 50 percent - grid.lua
--  [nomain] Human quantize notes (bundle)/sr_Human quantize notes (bundle).lua
--  [nomain] Human quantize notes (bundle)/sr_Human quantize notes function.lua
-- @about
--    # Description
--    * These scripts human quantize either all notes or selected notes in one or multiple items.
--    * In the arrange view (item view), selected events are not taken into account, because you can't see what is selected.
--    * In the inline editor, you MUST hover the mouse over the active inline editor, otherwise ALL events will 
--    be affected, instead of only the selected ones.
--    * When hovering an inline editor, only the take under the mouse cursor will be affected, regardles of the item selection.
--    * You can easily customize the values in the scripts.
--    * The scripts work in the MIDI editor, inline editor and arrange view.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923