-- @description Delete CC after edit cursor (bundle)
-- @version 1.32
-- @changelog
--   now includes "Delete all CCs after cursor"
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC1 after edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC2 after edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC7 after edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC11 after edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC64 after edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete all CCs after edit cursor.lua
--  [nomain] sr_Delete CC after edit cursor (bundle).lua
--  [nomain] sr_Delete CC after edit cursor function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that delete the CC after the edit cursor in one or multiple items
--    * These scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923