-- @description Delete CC (bundle)
-- @version 1.31
-- @changelog
--   now includes "Delete all CCs" scripts
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC64.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete all CCs.lua
--  [nomain] sr_Delete CC (bundle).lua
--  [nomain] sr_Delete CC function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that delete the complete CC lane in one or multiple items
--    * These scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923