-- @description Double notes (bundle)
-- @version 1.30
-- @changelog
--   The scripts are now available in a single bundle and the MIDI functions.lua is not necessary anymore. Instead the bundle has its own external function file. 
--   Furthermore, the scripts have been renamed to a more meaningful title.
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main] Double notes -24.lua
--  [main] Double notes -12.lua
--  [main] Double notes +12.lua
--  [main] Double notes +24.lua
--  [nomain] Double notes (bundle).lua
--  [nomain] Double notes function.lua
-- @about
--   # Description
--    This script bundle consists of scripts that doubles either all or selected notes in items.
--    The scripts work in arrangement, MIDI Editor and Inline Editor.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923