-- @description Double notes (bundle)
-- @version 1.31
-- @changelog
--   Fallback for no selected item
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Double notes -24.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Double notes -12.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Double notes +12.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Double notes +24.lua
--  [nomain] sr_Double notes (bundle).lua
--  [nomain] sr_Double notes function.lua
-- @about
--   # Description
--    This script bundle consists of scripts that doubles either all or selected notes in items.
--    The scripts work in arrangement, MIDI Editor and Inline Editor.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923