-- @description Delete CC before edit cursor (bundle)
-- @version 1.31
-- @changelog
--   code tydying
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC1 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC2 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC7 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC11 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC64 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete all CCs before edit cursor.lua
--  [nomain] sr_Delete CC before edit cursor (bundle).lua
--  [nomain] sr_Delete CC before edit cursor function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that delete the CC before the edit cursor in one or multiple items
--    * These scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923