-- @description Human quantize notes (bundle)
-- @version 1.50
-- @changelog
--   + the scripts now affect all notes and not only selected notes, when applied in the arrangement  (as it should be)
--   + several code optimizations
--   + fallback for non selected items in the arrange
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-4.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-4 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-8.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-8 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-16.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - 1-16 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Human quantize notes 50 percent - grid.lua
--  [nomain] sr_Human quantize notes (bundle).lua
--  [nomain] sr_Human quantize notes function.lua
-- @about
--    # Description
--    * This script bundle consists of various quantize scripts that affect either all or selected notes
--    * If you quantize notes from the arrangement, selected notes are not taken into account, because you can't see what is selected from
--    the arrangement. If you want to quantize from the inline editor, you MUST hover the mouse over the active inline editor, otherwise 
--    ALL notes will be affected, instead of only the selected ones.
--    * You can easily edit the scripts to adjust them to your needs or create new ones
--    * The scripts work in arrangement, MIDI editor and inline editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923