-- @description Increase CC (bundle)
-- @version 1.31
-- @changelog
--   Fallback for no selected item
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Increase CC1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Increase CC2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Increase CC7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Increase CC11.lua
--  [nomain] sr_Increase CC (bundle).lua
--  [nomain] sr_Increase CC function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that increase all or selected CC events in one or multiple items
--    * These scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923