-- @description Move CC to CC (bundle)
-- @version 1.31
-- @changelog
--   Fallback for no selected item
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC1 to CC2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC1 to CC7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC1 to CC11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC2 to CC1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC2 to CC7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC2 to CC11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC7 to CC1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC7 to CC2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC7 to CC11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC11 to CC1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC11 to CC2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Move CC11 to CC7.lua
--  [nomain] sr_Move CC to CC (bundle).lua
--  [nomain] sr_Move CC to CC function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that move the data of CC X to CC Y in one or multiple items
--    * These scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923
