-- @description Nudge notes (bundle)
-- @version 1.30
-- @changelog
--   The scripts are now available in a single bundle and the MIDI functions.lua is not necessary anymore. Instead the bundle includes its own external function file.  
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Nudge notes left by 10 ticks.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Nudge notes right by 10 ticks.lua
--  [nomain] sr_Nudge notes (bundle).lua
--  [nomain] sr_Nudge notes function.lua
-- @about
--    # Description
--    * This script bundles consists of 2 scripts that nudges either all notes or selected notes left/right.
--    * The amount of ticks can be adjusted in the scripts. That way, you can easily create different versions
--      that fit your personal needs. 
--    * The scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923