-- @description Quantize notes (bundle)
-- @version 1.40
-- @changelog
--   + fixed a lot of bugs and tidied the code
--   + if you quantize notes from the arrangement, selected notes are not taken into account, because you can't see what is selected from, 
--   the arrangement. Therefore support for the inline editor had to be re-written. When you want to quantize from the inline editor,
--   you MUST hover the mouse over the active inline editor, otherwise ALL notes will be quantized, instead of only the selected ones.
--   - had to get rid of the swing presets, since they don't work, have yet to find out what the problem is
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-4.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-4 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-8.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-8 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-16.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - 1-16 triplets.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Quantize notes - grid.lua
--  [nomain] sr_Quantize notes (bundle).lua
--  [nomain] sr_Quantize notes function.lua
-- @about
--    # Description
--    * This script bundle consists of various quantize scripts that affect either all or selected notes
--    * You can easily edit the scripts to adjust them to your needs or create new ones
--    * The scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923