-- @description Select CC within note selection (bundle)
-- @version 1.31
-- @changelog
--   Fallback for no selected item
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC1 within note selection.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC2 within note selection.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC7 within note selection.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC11 within note selection.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Select CC64 within note selection.lua
--  [nomain] sr_Select CC within note selection (bundle).lua
--  [nomain] sr_Select CC within note selection function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that select the CC within the boundaries of a note selection in one or multiple items
--    * Executing the scripts again toggles the CC selection
--    * These scripts work in arrangement, MIDI Editor and Inline Editor
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923