-- @description Transpose notes (bundle)
-- @version 1.41
-- @changelog
--   + code optimization
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -3.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -4.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -5.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -6.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -8.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -9.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -10.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes -12.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +1.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +2.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +3.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +4.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +5.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +6.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +7.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +8.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +9.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +10.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +11.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes +12.lua
--  [nomain] sr_Transpose notes (bundle).lua
--  [nomain] sr_Transpose notes function.lua
-- @about
--    # Description
--    * This script bundle consists of scripts that transpose either all notes or selected notes.
--    * If you tranpose notes from the arrangement, selected notes are not taken into account, because you can't see what is selected from
--    the arrangement. If you want to tranpose from the inline editor, you MUST hover the mouse over the active inline editor, otherwise 
--    ALL notes will be affected, instead of only the selected ones.
--    * You can easily edit the scripts to adjust them to your needs or create new ones
--    * The scripts work in arrangement, MIDI editor and inline editor.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923