-- @description Transpose notes
-- @version 1.0
-- @author Stephan Römer
-- @about
--     # Description
--     - this package contains several scripts to transpose notes up and down
-- @metapackage
-- @provides 
--   [main=main,midi_editor,midi_inlineeditor] sr_Transpose notes *.lua 
--   [nomain] sr_Transpose function.lua

