-- @description Delete CC before edit cursor (bundle)
-- @version 1.60
-- @changelog
--   + the scripts are now located in their own folder
--   * smaller bug fixes and improvements
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC1 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC2 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC7 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC11 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete CC64 before edit cursor.lua
--  [main=main,midi_editor,midi_inlineeditor] sr_Delete all CCs before edit cursor.lua
--  [nomain] sr_Delete CC before edit cursor (bundle).lua
--  [nomain] sr_Delete CC before edit cursor function.lua
-- @about
--    # Description
--    * These scripts will delete all events in a specific CC lane or all CC lanes before the edit cursor in one or multiple items.
--    * When hovering an inline editor, only the take under the mouse cursor will be affected, regardles of the item selection.
--    * You can easily customize the values in the scripts.
--    * The scripts work in the MIDI editor, inline editor and arrange view.
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923