-- @description Remove send from selected track(s) (bundle)
-- @version 1.1
-- @changelog
--   switched to external function file and put all scripts in a bundle
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [main] sr_Remove send 1 from selected track(s).lua
--  [main] sr_Remove send 2 from selected track(s).lua
--  [main] sr_Remove send 3 from selected track(s).lua
--  [main] sr_Remove send 4 from selected track(s).lua
--  [nomain] sr_Remove send from selected track(s) (bundle).lua
--  [nomain] sr_Remove send from selected track(s) function.lua
-- @about
--   # Description
--   This script bundle consists of 4 scripts that remove sends 1-4 from the selected track(s)
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923