-- @description Send selected track(s) to FX track
-- @version 1.11
-- @changelog
--   switched to external function file and put all scripts in a bundle
-- @author Stephan Römer
-- @metapackage
-- @provides
--  [nomain] .
-- 	[nomain] sr_Send selected track(s) to FX track function.lua
-- 	[main] sr_Send selected track(s) to FX1.lua
-- 	[main] sr_Send selected track(s) to FX2.lua
-- 	[main] sr_Send selected track(s) to FX3.lua
-- 	[main] sr_Send selected track(s) to FX4.lua
-- @about
--   # Description
--   This script bundle consists of 4 scripts that will send all selected tracks to an FX track prefixed with FX1-4
-- @link Forum Thread https://forums.cockos.com/showthread.php?p=1923923